// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package tenantdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantEmployeeRole = `-- name: GetTenantEmployeeRole :one
SELECT 
    e.user_id,
    e.is_active,
    r.id AS role_id,
    r.name AS role_name,
    r.permissions
FROM employees e
JOIN roles r ON e.roleId = r.id
WHERE e.user_id = $1 AND e.isActive = true 
LIMIT 1
`

type GetTenantEmployeeRoleRow struct {
	UserID      string      `db:"user_id" json:"user_id"`
	IsActive    pgtype.Bool `db:"is_active" json:"is_active"`
	RoleID      string      `db:"role_id" json:"role_id"`
	RoleName    string      `db:"role_name" json:"role_name"`
	Permissions []byte      `db:"permissions" json:"permissions"`
}

// Mengambil data lengkap karyawan beserta role dan permission-nya
// Digunakan saat proses Select Store untuk mengisi klaim JWT Tenant
func (q *Queries) GetTenantEmployeeRole(ctx context.Context, userID string) (GetTenantEmployeeRoleRow, error) {
	row := q.db.QueryRow(ctx, getTenantEmployeeRole, userID)
	var i GetTenantEmployeeRoleRow
	err := row.Scan(
		&i.UserID,
		&i.IsActive,
		&i.RoleID,
		&i.RoleName,
		&i.Permissions,
	)
	return i, err
}

const listEmployeesWithRoles = `-- name: ListEmployeesWithRoles :many
SELECT 
    e.id, 
    e.full_name, 
    e.position, 
    e.is_active, 
    r.name as role_name
FROM employees e
LEFT JOIN roles r ON e.roleId = r.id
ORDER BY e.full_name ASC
`

type ListEmployeesWithRolesRow struct {
	ID       string      `db:"id" json:"id"`
	FullName string      `db:"full_name" json:"full_name"`
	Position pgtype.Text `db:"position" json:"position"`
	IsActive pgtype.Bool `db:"is_active" json:"is_active"`
	RoleName pgtype.Text `db:"role_name" json:"role_name"`
}

// Mengambil daftar semua karyawan di dalam toko/tenant
func (q *Queries) ListEmployeesWithRoles(ctx context.Context) ([]ListEmployeesWithRolesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesWithRolesRow
	for rows.Next() {
		var i ListEmployeesWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Position,
			&i.IsActive,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
