// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID         string           `db:"id" json:"id"`
	UserID     string           `db:"user_id" json:"user_id"`
	FullName   string           `db:"full_name" json:"full_name"`
	Position   pgtype.Text      `db:"position" json:"position"`
	Phone      pgtype.Text      `db:"phone" json:"phone"`
	Address    pgtype.Text      `db:"address" json:"address"`
	Photo      pgtype.Text      `db:"photo" json:"photo"`
	CitizenID  pgtype.Text      `db:"citizen_id" json:"citizen_id"`
	BaseSalary pgtype.Numeric   `db:"base_salary" json:"base_salary"`
	JoinDate   pgtype.Timestamp `db:"join_date" json:"join_date"`
	IsActive   pgtype.Bool      `db:"is_active" json:"is_active"`
	RoleID     string           `db:"role_id" json:"role_id"`
}

type Role struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Permissions []byte `db:"permissions" json:"permissions"`
}

type StoreProfile struct {
	ID          string           `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	Address     pgtype.Text      `db:"address" json:"address"`
	Phone       pgtype.Text      `db:"phone" json:"phone"`
	Email       pgtype.Text      `db:"email" json:"email"`
	TaxID       pgtype.Text      `db:"tax_id" json:"tax_id"`
	LogoUrl     pgtype.Text      `db:"logo_url" json:"logo_url"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
