// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package tenantdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreProfile = `-- name: CreateStoreProfile :one
INSERT INTO store_profiles (
    store_id
) VALUES (
    $1
) RETURNING store_id
`

func (q *Queries) CreateStoreProfile(ctx context.Context, storeID string) (string, error) {
	row := q.db.QueryRow(ctx, createStoreProfile, storeID)
	var store_id string
	err := row.Scan(&store_id)
	return store_id, err
}

const getStoreProfile = `-- name: GetStoreProfile :one
SELECT 
    s.id as store_id,
    s.name as store_name,
    sp.description,
    sp.address,
    sp.phone,
    sp.email,
    sp.tax_id,
    sp.logo_url,
    sp.receipt_footer
FROM public.stores s
LEFT JOIN store_profiles sp ON s.id = sp.store_id
WHERE s.id = $1 LIMIT 1
`

type GetStoreProfileRow struct {
	StoreID       string      `db:"store_id" json:"store_id"`
	StoreName     string      `db:"store_name" json:"store_name"`
	Description   pgtype.Text `db:"description" json:"description"`
	Address       pgtype.Text `db:"address" json:"address"`
	Phone         pgtype.Text `db:"phone" json:"phone"`
	Email         pgtype.Text `db:"email" json:"email"`
	TaxID         pgtype.Text `db:"tax_id" json:"tax_id"`
	LogoUrl       pgtype.Text `db:"logo_url" json:"logo_url"`
	ReceiptFooter pgtype.Text `db:"receipt_footer" json:"receipt_footer"`
}

func (q *Queries) GetStoreProfile(ctx context.Context, id string) (GetStoreProfileRow, error) {
	row := q.db.QueryRow(ctx, getStoreProfile, id)
	var i GetStoreProfileRow
	err := row.Scan(
		&i.StoreID,
		&i.StoreName,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.ReceiptFooter,
	)
	return i, err
}

const updateStoreProfile = `-- name: UpdateStoreProfile :one
UPDATE store_profiles
SET 
    description = $1,
    address = $2,
    phone = $3,
    email = $4,
    tax_id = $5,
    logo_url = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE store_id = $7
RETURNING store_id, description, address, phone, email, tax_id, logo_url, receipt_footer, updated_at
`

type UpdateStoreProfileParams struct {
	Description pgtype.Text `db:"description" json:"description"`
	Address     pgtype.Text `db:"address" json:"address"`
	Phone       pgtype.Text `db:"phone" json:"phone"`
	Email       pgtype.Text `db:"email" json:"email"`
	TaxID       pgtype.Text `db:"tax_id" json:"tax_id"`
	LogoUrl     pgtype.Text `db:"logo_url" json:"logo_url"`
	StoreID     string      `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateStoreProfile(ctx context.Context, arg UpdateStoreProfileParams) (StoreProfile, error) {
	row := q.db.QueryRow(ctx, updateStoreProfile,
		arg.Description,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.TaxID,
		arg.LogoUrl,
		arg.StoreID,
	)
	var i StoreProfile
	err := row.Scan(
		&i.StoreID,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.ReceiptFooter,
		&i.UpdatedAt,
	)
	return i, err
}
