// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package tenantdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStoreProfile = `-- name: GetStoreProfile :one
SELECT id, name, description, address, phone, email, tax_id, logo_url, created_at, updated_at FROM store_profiles LIMIT 1
`

func (q *Queries) GetStoreProfile(ctx context.Context) (StoreProfile, error) {
	row := q.db.QueryRow(ctx, getStoreProfile)
	var i StoreProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoreProfile = `-- name: UpdateStoreProfile :exec
UPDATE store_profiles 
SET name = $2, description = $3, address = $4, phone = $5, email = $6, tax_id = $7, logo_url = $8, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateStoreProfileParams struct {
	ID          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	Address     pgtype.Text `db:"address" json:"address"`
	Phone       pgtype.Text `db:"phone" json:"phone"`
	Email       pgtype.Text `db:"email" json:"email"`
	TaxID       pgtype.Text `db:"tax_id" json:"tax_id"`
	LogoUrl     pgtype.Text `db:"logo_url" json:"logo_url"`
}

func (q *Queries) UpdateStoreProfile(ctx context.Context, arg UpdateStoreProfileParams) error {
	_, err := q.db.Exec(ctx, updateStoreProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.TaxID,
		arg.LogoUrl,
	)
	return err
}
