// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	GetStoreProfile(ctx context.Context) (StoreProfile, error)
	UpdateStoreProfile(ctx context.Context, arg UpdateStoreProfileParams) error
}

var _ Querier = (*Queries)(nil)
