// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package tenantdb

import (
	"context"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (id, user_id, full_name, role_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, full_name, position, phone, address, photo, citizen_id, base_salary, join_date, is_active, role_id
`

type CreateEmployeeParams struct {
	ID       string `db:"id" json:"id"`
	UserID   string `db:"user_id" json:"user_id"`
	FullName string `db:"full_name" json:"full_name"`
	RoleID   string `db:"role_id" json:"role_id"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.RoleID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Position,
		&i.Phone,
		&i.Address,
		&i.Photo,
		&i.CitizenID,
		&i.BaseSalary,
		&i.JoinDate,
		&i.IsActive,
		&i.RoleID,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, name, permissions)
VALUES ($1, $2, $3)
RETURNING id, name, permissions
`

type CreateRoleParams struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Permissions []byte `db:"permissions" json:"permissions"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Name, arg.Permissions)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Permissions)
	return i, err
}
