// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package internal

import (
	"context"
)

// iteratorForCreateManyUsersByAdmin implements pgx.CopyFromSource.
type iteratorForCreateManyUsersByAdmin struct {
	rows                 []CreateManyUsersByAdminParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateManyUsersByAdmin) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateManyUsersByAdmin) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RoleID,
		r.rows[0].Name,
		r.rows[0].Email,
		r.rows[0].IsActive,
	}, nil
}

func (r iteratorForCreateManyUsersByAdmin) Err() error {
	return nil
}

func (q *Queries) CreateManyUsersByAdmin(ctx context.Context, arg []CreateManyUsersByAdminParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"id", "role_id", "name", "email", "is_active"}, &iteratorForCreateManyUsersByAdmin{rows: arg})
}
