// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package internal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Permissions []byte `json:"permissions"`
}

type User struct {
	ID           string             `json:"id"`
	RoleID       pgtype.Text        `json:"role_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserAccount struct {
	ID                string      `json:"id"`
	UserID            string      `json:"user_id"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int8 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
}
