// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package internal

import (
	"context"
)

type Querier interface {
	CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) (SystemAdmin, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id string) error
	GetSystemAdminByEmail(ctx context.Context, email string) (GetSystemAdminByEmailRow, error)
	GetSystemAdminByID(ctx context.Context, id string) (GetSystemAdminByIDRow, error)
	ListSystemAdmins(ctx context.Context) ([]ListSystemAdminsRow, error)
	UpdateSystemAdminLevel(ctx context.Context, arg UpdateSystemAdminLevelParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
