// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package internal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemAdmin = `-- name: CreateSystemAdmin :one
INSERT INTO public.system_admins (user_id, level)
VALUES ($1, $2)
RETURNING id, user_id, level, created_at
`

type CreateSystemAdminParams struct {
	UserID string     `json:"user_id"`
	Level  AdminLevel `json:"level"`
}

func (q *Queries) CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, createSystemAdmin, arg.UserID, arg.Level)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO public.users (name, email, password_hash, image)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, email_verified, image, password_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Image        pgtype.Text `json:"image"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM public.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getSystemAdminByEmail = `-- name: GetSystemAdminByEmail :one
SELECT 
    u.id, 
    u.name, 
    u.email, 
    u.password_hash, 
    u.is_active, 
    sa.level AS admin_level
FROM public.users u
JOIN public.system_admins sa ON u.id = sa.user_id
WHERE u.email = $1 LIMIT 1
`

type GetSystemAdminByEmailRow struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
	AdminLevel   AdminLevel  `json:"admin_level"`
}

func (q *Queries) GetSystemAdminByEmail(ctx context.Context, email string) (GetSystemAdminByEmailRow, error) {
	row := q.db.QueryRow(ctx, getSystemAdminByEmail, email)
	var i GetSystemAdminByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.AdminLevel,
	)
	return i, err
}

const getSystemAdminByID = `-- name: GetSystemAdminByID :one
SELECT 
    u.id, 
    u.name, 
    u.email, 
    u.image, 
    u.is_active, 
    u.created_at,
    sa.level AS admin_level
FROM public.users u
JOIN public.system_admins sa ON u.id = sa.user_id
WHERE u.id = $1 LIMIT 1
`

type GetSystemAdminByIDRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	Image      pgtype.Text        `json:"image"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AdminLevel AdminLevel         `json:"admin_level"`
}

func (q *Queries) GetSystemAdminByID(ctx context.Context, id string) (GetSystemAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getSystemAdminByID, id)
	var i GetSystemAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Image,
		&i.IsActive,
		&i.CreatedAt,
		&i.AdminLevel,
	)
	return i, err
}

const listSystemAdmins = `-- name: ListSystemAdmins :many
SELECT 
    u.id, 
    u.name, 
    u.email, 
    u.is_active, 
    sa.level AS admin_level,
    u.created_at
FROM public.users u
JOIN public.system_admins sa ON u.id = sa.user_id
ORDER BY u.created_at DESC
`

type ListSystemAdminsRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	IsActive   bool               `json:"is_active"`
	AdminLevel AdminLevel         `json:"admin_level"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSystemAdmins(ctx context.Context) ([]ListSystemAdminsRow, error) {
	rows, err := q.db.Query(ctx, listSystemAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemAdminsRow
	for rows.Next() {
		var i ListSystemAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsActive,
			&i.AdminLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemAdminLevel = `-- name: UpdateSystemAdminLevel :exec
UPDATE public.system_admins
SET level = $2
WHERE user_id = $1
`

type UpdateSystemAdminLevelParams struct {
	UserID string     `json:"user_id"`
	Level  AdminLevel `json:"level"`
}

func (q *Queries) UpdateSystemAdminLevel(ctx context.Context, arg UpdateSystemAdminLevelParams) error {
	_, err := q.db.Exec(ctx, updateSystemAdminLevel, arg.UserID, arg.Level)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE public.users
SET 
    name = $2,
    image = $3,
    is_active = $4
WHERE id = $1
RETURNING id, name, email, email_verified, image, password_hash, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Image    pgtype.Text `json:"image"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
