basePath: /api/v1
definitions:
  internal.AdminLevel:
    enum:
    - SUPERADMIN
    - ADMIN
    type: string
    x-enum-varnames:
    - AdminLevelSUPERADMIN
    - AdminLevelADMIN
  internal.GetSystemAdminByIDRow:
    properties:
      admin_level:
        $ref: '#/definitions/internal.AdminLevel'
      created_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      email:
        type: string
      id:
        type: string
      image:
        $ref: '#/definitions/pgtype.Text'
      is_active:
        type: boolean
      name:
        type: string
    type: object
  internal.ListSystemAdminsRow:
    properties:
      admin_level:
        $ref: '#/definitions/internal.AdminLevel'
      created_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
    type: object
  modules_users.CreateSystemAdminRequest:
    properties:
      email:
        example: abu@example.com
        type: string
      level:
        enum:
        - SUPERADMIN
        - ADMIN
        example: SUPERADMIN
        type: string
      name:
        example: Abunawas
        type: string
      password:
        example: rahasia123
        type: string
    required:
    - level
    type: object
  modules_users.UpdateSystemAdminRequest:
    properties:
      is_active:
        example: true
        type: boolean
      level:
        enum:
        - SUPERADMIN
        - ADMIN
        example: ADMIN
        type: string
      name:
        example: Abunawas Updated
        type: string
    required:
    - level
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    format: int32
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Text:
    properties:
      string:
        type: string
      valid:
        type: boolean
    type: object
  pgtype.Timestamptz:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        type: string
      valid:
        type: boolean
    type: object
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TB App API
  version: "1.0"
paths:
  /users:
    get:
      description: Menampilkan semua system admin yang terdaftar di sistem.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal.ListSystemAdminsRow'
            type: array
      summary: Mengambil daftar semua system admin
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Membuat user dan menetapkannya sebagai system admin. Jika password
        diisi, akan di-hash.
      parameters:
      - description: Data Admin
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/modules_users.CreateSystemAdminRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal.GetSystemAdminByIDRow'
      summary: Mendaftarkan system admin baru
      tags:
      - users
  /users/{id}:
    delete:
      description: Menghapus user dari sistem berdasarkan ID. Menghapus otomatis akses
        admin karena Cascade.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Menghapus user dan admin
      tags:
      - users
    get:
      description: Menampilkan informasi lengkap admin tertentu.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.GetSystemAdminByIDRow'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Mengambil detail admin berdasarkan ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Mengubah informasi profil, foto, atau level admin.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Data Update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/modules_users.UpdateSystemAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.GetSystemAdminByIDRow'
      summary: Memperbarui data system admin
      tags:
      - users
swagger: "2.0"
