// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// ==========================================
	// DOMAIN: Otoritas Akses Toko (Tenant Bridge)
	// ==========================================
	// Digunakan oleh: Modul Tenant (saat buat toko) & Modul Employee (saat tambah staf)
	AssignUserToStore(ctx context.Context, arg AssignUserToStoreParams) (UserStoreAccess, error)
	// ==========================================
	// DOMAIN: Identitas Pengguna (Global)
	// ==========================================
	// Digunakan oleh: Modul Sysadmin (Global) & Modul Tenant (Onboarding)
	CreateBaseUser(ctx context.Context, arg CreateBaseUserParams) (User, error)
	// ==========================================
	// DOMAIN: Otoritas Admin Sistem (Global)
	// ==========================================
	// Digunakan oleh: Modul Sysadmin
	CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) (SystemAdmin, error)
	DeleteSystemAdmin(ctx context.Context, id string) error
	// Catatan: Akan memicu CASCADE ke system_admins & user_store_access
	DeleteUser(ctx context.Context, id string) error
	// Digunakan oleh: Middleware untuk cek apakah user punya akses Superadmin
	GetAdminAccess(ctx context.Context, userID string) (AdminLevel, error)
	GetSystemAdminByID(ctx context.Context, id string) (GetSystemAdminByIDRow, error)
	// Digunakan untuk: Proses login awal
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Digunakan untuk: Fetch data profil user
	GetUserById(ctx context.Context, id string) (User, error)
	// Digunakan untuk: Layar "Pilih Toko" setelah login
	GetUserStores(ctx context.Context, userID string) ([]GetUserStoresRow, error)
	// Menampilkan daftar admin beserta info user-nya (Join)
	ListAllSystemAdmins(ctx context.Context) ([]ListAllSystemAdminsRow, error)
	UpdateAdminLevel(ctx context.Context, arg UpdateAdminLevelParams) error
	UpdateSystemAdmin(ctx context.Context, arg UpdateSystemAdminParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Digunakan oleh: Modul Shared (Profile)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Digunakan untuk: Memblokir atau mengaktifkan user secara global
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
