// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package db

import (
	"context"
)

const createStore = `-- name: CreateStore :one
INSERT INTO public.stores (name, slug, schema_name)
VALUES ($1, $2, $3)
RETURNING id, name, slug, schema_name, is_active, created_at
`

type CreateStoreParams struct {
	Name       string `db:"name" json:"name"`
	Slug       string `db:"slug" json:"slug"`
	SchemaName string `db:"schema_name" json:"schema_name"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.Name, arg.Slug, arg.SchemaName)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createUserStoreAccess = `-- name: CreateUserStoreAccess :exec
INSERT INTO public.user_store_access (user_id, store_id)
VALUES ($1, $2)
`

type CreateUserStoreAccessParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	StoreID string `db:"store_id" json:"store_id"`
}

func (q *Queries) CreateUserStoreAccess(ctx context.Context, arg CreateUserStoreAccessParams) error {
	_, err := q.db.Exec(ctx, createUserStoreAccess, arg.UserID, arg.StoreID)
	return err
}

const getStoreBySlug = `-- name: GetStoreBySlug :one
SELECT id, name, slug, schema_name, is_active, created_at FROM public.stores WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreBySlug, slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateStoreName = `-- name: UpdateStoreName :exec
UPDATE stores 
SET name = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

type UpdateStoreNameParams struct {
	ID   string `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) UpdateStoreName(ctx context.Context, arg UpdateStoreNameParams) error {
	_, err := q.db.Exec(ctx, updateStoreName, arg.ID, arg.Name)
	return err
}
