// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserToStore = `-- name: AssignUserToStore :one

INSERT INTO public.user_store_access (
    user_id, 
    store_id, 
    is_active
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, store_id, is_active, assigned_at
`

type AssignUserToStoreParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	StoreID  string `db:"store_id" json:"store_id"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

// ==========================================
// DOMAIN: Otoritas Akses Toko (Tenant Bridge)
// ==========================================
// Digunakan oleh: Modul Tenant (saat buat toko) & Modul Employee (saat tambah staf)
func (q *Queries) AssignUserToStore(ctx context.Context, arg AssignUserToStoreParams) (UserStoreAccess, error) {
	row := q.db.QueryRow(ctx, assignUserToStore, arg.UserID, arg.StoreID, arg.IsActive)
	var i UserStoreAccess
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.IsActive,
		&i.AssignedAt,
	)
	return i, err
}

const createBaseUser = `-- name: CreateBaseUser :one

INSERT INTO public.users (
    name, 
    email, 
    password_hash, 
    image
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, email, email_verified, image, password_hash, is_active, created_at, updated_at
`

type CreateBaseUserParams struct {
	Name         string      `db:"name" json:"name"`
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	Image        pgtype.Text `db:"image" json:"image"`
}

// ==========================================
// DOMAIN: Identitas Pengguna (Global)
// ==========================================
// Digunakan oleh: Modul Sysadmin (Global) & Modul Tenant (Onboarding)
func (q *Queries) CreateBaseUser(ctx context.Context, arg CreateBaseUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createBaseUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSystemAdmin = `-- name: CreateSystemAdmin :one

INSERT INTO public.system_admins (
    user_id, 
    level
) VALUES (
    $1, $2
) RETURNING id, user_id, level, created_at
`

type CreateSystemAdminParams struct {
	UserID string     `db:"user_id" json:"user_id"`
	Level  AdminLevel `db:"level" json:"level"`
}

// ==========================================
// DOMAIN: Otoritas Admin Sistem (Global)
// ==========================================
// Digunakan oleh: Modul Sysadmin
func (q *Queries) CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, createSystemAdmin, arg.UserID, arg.Level)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSystemAdmin = `-- name: DeleteSystemAdmin :exec
DELETE FROM public.users WHERE id = $1
`

func (q *Queries) DeleteSystemAdmin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSystemAdmin, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM public.users
WHERE id = $1
`

// Catatan: Akan memicu CASCADE ke system_admins & user_store_access
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAdminAccess = `-- name: GetAdminAccess :one
SELECT level FROM public.system_admins
WHERE user_id = $1 LIMIT 1
`

// Digunakan oleh: Middleware untuk cek apakah user punya akses Superadmin
func (q *Queries) GetAdminAccess(ctx context.Context, userID string) (AdminLevel, error) {
	row := q.db.QueryRow(ctx, getAdminAccess, userID)
	var level AdminLevel
	err := row.Scan(&level)
	return level, err
}

const getSystemAdminByID = `-- name: GetSystemAdminByID :one
SELECT u.id, u.name, u.email, u.is_active, sa.level, u.created_at
FROM public.users u
JOIN public.system_admins sa ON u.id = sa.user_id
WHERE u.id = $1 LIMIT 1
`

type GetSystemAdminByIDRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	Level     AdminLevel         `db:"level" json:"level"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetSystemAdminByID(ctx context.Context, id string) (GetSystemAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getSystemAdminByID, id)
	var i GetSystemAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsActive,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, image, password_hash, is_active, created_at, updated_at FROM public.users
WHERE email = $1 LIMIT 1
`

// Digunakan untuk: Proses login awal
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, email_verified, image, password_hash, is_active, created_at, updated_at FROM public.users
WHERE id = $1 LIMIT 1
`

// Digunakan untuk: Fetch data profil user
func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStores = `-- name: GetUserStores :many
SELECT 
    s.id, s.name, s.slug, s.schema_name, 
    usa.is_active as access_status
FROM public.stores s
JOIN public.user_store_access usa ON s.id = usa.store_id
WHERE usa.user_id = $1 AND s.is_active = true
`

type GetUserStoresRow struct {
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Slug         string `db:"slug" json:"slug"`
	SchemaName   string `db:"schema_name" json:"schema_name"`
	AccessStatus bool   `db:"access_status" json:"access_status"`
}

// Digunakan untuk: Layar "Pilih Toko" setelah login
func (q *Queries) GetUserStores(ctx context.Context, userID string) ([]GetUserStoresRow, error) {
	rows, err := q.db.Query(ctx, getUserStores, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserStoresRow
	for rows.Next() {
		var i GetUserStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SchemaName,
			&i.AccessStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSystemAdmins = `-- name: ListAllSystemAdmins :many
SELECT 
    u.id, u.name, u.email, u.image, u.is_active,
    sa.level, sa.created_at as admin_since
FROM public.users u
JOIN public.system_admins sa ON u.id = sa.user_id
ORDER BY sa.created_at DESC
`

type ListAllSystemAdminsRow struct {
	ID         string             `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Email      string             `db:"email" json:"email"`
	Image      pgtype.Text        `db:"image" json:"image"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	Level      AdminLevel         `db:"level" json:"level"`
	AdminSince pgtype.Timestamptz `db:"admin_since" json:"admin_since"`
}

// Menampilkan daftar admin beserta info user-nya (Join)
func (q *Queries) ListAllSystemAdmins(ctx context.Context) ([]ListAllSystemAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAllSystemAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSystemAdminsRow
	for rows.Next() {
		var i ListAllSystemAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Image,
			&i.IsActive,
			&i.Level,
			&i.AdminSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminLevel = `-- name: UpdateAdminLevel :exec
UPDATE public.system_admins
SET level = $2
WHERE user_id = $1
`

type UpdateAdminLevelParams struct {
	UserID string     `db:"user_id" json:"user_id"`
	Level  AdminLevel `db:"level" json:"level"`
}

func (q *Queries) UpdateAdminLevel(ctx context.Context, arg UpdateAdminLevelParams) error {
	_, err := q.db.Exec(ctx, updateAdminLevel, arg.UserID, arg.Level)
	return err
}

const updateSystemAdmin = `-- name: UpdateSystemAdmin :exec
UPDATE public.users 
SET name = $2, is_active = $3
WHERE id = $1
`

type UpdateSystemAdminParams struct {
	ID       string `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateSystemAdmin(ctx context.Context, arg UpdateSystemAdminParams) error {
	_, err := q.db.Exec(ctx, updateSystemAdmin, arg.ID, arg.Name, arg.IsActive)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE public.users 
SET email = $2 
WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    string `db:"id" json:"id"`
	Email string `db:"email" json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE public.users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string      `db:"id" json:"id"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE public.users
SET 
    name = $2,
    image = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, email, email_verified, image, password_hash, is_active, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID    string      `db:"id" json:"id"`
	Name  string      `db:"name" json:"name"`
	Image pgtype.Text `db:"image" json:"image"`
}

// Digunakan oleh: Modul Shared (Profile)
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Image)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE public.users
SET is_active = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID       string `db:"id" json:"id"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

// Digunakan untuk: Memblokir atau mengaktifkan user secara global
func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.IsActive)
	return err
}
